name: e2e
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Atualizando para a versão 20 do Node.js
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
    # ação Cypress com cypress.config.js
    - name: Cypress run
      uses: cypress-io/github-action@v2.8.2
      with:
        config-file: cypress.config.js
